### ISSUE TITLE
N815 is not being reported

### ISSUE THREAD

**Issue by cyberfox1** [PyCQA/pep8-naming#188] opened 2021-12-01 02:01 UTC
Attributes of a class should be checked against camelCase rules.

badName = 'bob'

class AClass():
    
    def __init__(self):
        self.fooBar = 42

    def camelCase():
        pass

$ flake8 --ignore="H301" aclass.py 
aclass.py:1:2: N816 variable 'badName' in global scope should not be mixedCase
aclass.py:3:1: E302 expected 2 blank lines, found 1
aclass.py:4:1: W293 blank line contains whitespace
aclass.py:8:10: N802 function name 'camelCase' should be lowercase

I get errors for everything except fooBar, but it should according to N815.

Installed plugins: hacking.core: 0.0.1, mccabe: 0.6.1, naming: 0.10.0, pycodestyle: 2.6.0, pyflakes: 2.2.0

**Comment by sigmavirus24** [comment] 2021-12-02 01:13
Duplicate of #187

**Closed by sigmavirus24** 2021-12-02 01:13 UTC
