### ISSUE TITLE
Regression in 0.8.0 - Underscore argument names report [N803]

### ISSUE THREAD

**Issue by xlevus** [PyCQA/pep8-naming#104] opened 2019-01-30 14:45 UTC
```# test.py
def foo(_):
    pass
```
```
$ flake8 test.py
test.py:1:10: N803 argument name '_' should be lowercase
```
This persists with `flake8` versions 3.7.1, 3.7.0 and 3.6.0.
Does not appear to be an issue with `pep8-naming` 0.7.0

**Comment by 5j9** [comment] 2019-01-30 14:47
Duplicate of #95

**Closed** 2019-01-30 14:47 UTC

**Comment by sigmavirus24** [comment] 2019-01-30 16:01
In the future, please search **closed and** open issues before creating new ones that are duplicates.
