### ISSUE TITLE
N816 does not make sense

### ISSUE THREAD

**Issue by abcdenis** [PyCQA/pep8-naming#192] opened 2022-01-28 12:02 UTC
Hi,
it triggers on mixed case names only but description points to PEP8 which requires global variables to be upper-cased.
https://www.python.org/dev/peps/pep-0008/#constants

As a result, pep8-naming won't find errors in
```python
name = 'GLOBAL VAR'
print(name)
```

It will be nice to check global variables for upper case only.

**Comment by sigmavirus24** [comment] 2022-01-28 12:33
Duplicate of #49

**Closed by sigmavirus24** 2022-01-28 12:33 UTC
